version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres
    ports:
      - '5432:5432'
    env_file:
      - docker.env

  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - rmq-1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  postgres:
    driver: bridge
  rmq-1:
    driver: bridge
