version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres
    ports:
      - '5432:5432'
    env_file:
      - ./postgres.env

  rmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - rmq-1
    env_file:
      - ./rabbitmq.env

networks:
  postgres:
    driver: bridge
  rmq-1:
    driver: bridge
